### ISSUE TITLE
Property error on compile

### ISSUE THREAD

**Issue by russback** [twbs/bootstrap-sass#932]
I am pulling in components rather than the complete library:

````
// Core variables and mixins
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/variables";
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins";

// Reset and dependencies
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/normalize";
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/print";
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/glyphicons";

// Core CSS
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/scaffolding";
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/type";
// etc...
````

Using gulp-ruby-sass I'm getting an error:

````
[Error running Gulp] error /Users/russback/VagrantSites/dendash.com/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_glyphicons.scss (Line 13: Properties are only allowed within rules, directives, mixin includes, or other properties.)
````

If I comment out that component file I get a similar error from _responsive-utilities.scss and if I comment out both of these files it all compiles fine.

Any suggestions?

**Comment by glebm** [comment]
What are your versions of bootstrap-sass, gulp-ruby-sass, and the sass gem?

**Comment by russback** [comment]
bootstrap-sass: 3.3.5
gulp-ruby-sass: 1.4.28

'sudo gem list --local' shows 'sass (3.4.15, 3.4.14, 3.4.12, 3.4.9)'

**Comment by glebm** [comment]
Instead of `sudo gem list --local` please check with `sass --version` (that's what gulp-ruby-sass [uses](https://github.com/sindresorhus/gulp-ruby-sass/blob/9956ec4eb25703fcdea360ebaa079ad479c50d3a/index.js#L80)). Also, the latest version of gulp-ruby-sass seems to be [1.0.5](https://www.npmjs.com/package/gulp-ruby-sass).

**Comment by russback** [comment]
Sass 3.3.2 (Maptastic Maple)

Will check latest gulp-ruby-sass now.

**Comment by glebm** [comment]
Please upgrade sass to 3.4.15, that should resolve the issue.

**Comment by russback** [comment]
Hmmm... 'sudo gem install sass' reports 'Successfully installed sass-3.4.15' but 'sass -v' still shows 'Sass 3.3.2 (Maptastic Maple)'

**Comment by glebm** [comment]
What does `which sass` report? Can you install without sudo?

**Comment by russback** [comment]
`/usr/bin/sass` returns `/usr/bin/sass`, `which gem` returns `/usr/bin/gem`. 

I can't install without sudo.

**Comment by glebm** [comment]
You may want to ask about Sass on Stack Overflow. Sass v3.3.4 is the minimum version required, latest is recommended.
